### ISSUE TITLE
Missing base ZH locale?

### ISSUE THREAD

**Issue by redross** [svenfuchs/rails-i18n#1050]
I've relied on this behavior for a long time:
```
 By default all country variants (en-US) will fallback to languages first (e.g en) and you only need to specify something if you want to fallback differently
 ```
It works great for all kinds of locales (es/de/en), but for some reason - not zh. Looking at rails/locales I see: `zh-CN.yml  zh-HK.yml  zh-TW.yml  zh-YUE.yml`, but no `zh.yml` variant? This seems inconsistent. If people can agree on what the base en/es locale should be, why can't the same be done for zh? A fix would be to copy zh-CN.yml as zh.yml (even though I support TW/HK communities - I doubt anyone would argue, that the CN variant is the most common/expected)

**Comment by johnnyshields** [comment]
zh-CN and zh-TW are two fundamentally different scripts, unlike es-ES/es-MX or pt-PT/pt-BR. I don't think it makes sense to this. What we should consider doing instead is switch to the zh-Hans / zh-Hant script convention, rather than using country codes to indicate scripts.

**Comment by redross** [comment]
Basically if I invent "en-redross" english variation, that is nothing like english. Does that mean everybody should drop en.yml locale since not all variations are actually english?

**Comment by johnnyshields** [comment]
`en-redross` is not an ISO 639 / IANA standard. `zh-Hant` and `zh-Hans` are.

It is a best practice to use `zh-Hant` and `zh-Hans` to avoid ambiguity and political debates. Adding `zh` increases ambiguity.

**Comment by redross** [comment]
Just to double check: am I looking at the wrong place (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry):
```
Type: language
Subtag: zh
Description: Chinese
Added: 2005-10-16
Scope: macrolanguage
```

`zh` subtag is mentioned as a language :thinking: 

Either way, thank you for your responses. I doubt we'll want to change urls on the site from `/zh/smth`, to `/zh-hant/smth`, so most likely I'll need to do some trickery.

**Comment by sunny** [comment]
Perhaps you can try using fallbacks? E.g. `I18n.fallbacks[:zh] = [:"zh-hant"]`

**Comment by redross** [comment]
Yes, thank you - that was my initial plan. But then I stumbled upon "By default all country variants (en-US) will fallback to languages first (e.g en)" (not sure if it was part of documentation or just some post) and it felt like "wait a minute is this not working or am I doing something wrong". I guess the omission of base language is not accidental - so I'm closing this issue for now. If I'll notice the same sentence in rails guides or documentation, I'll try suggesting an edit warning that there are possible edge cases where the default fallback doesn't happen.
