### ISSUE TITLE
Passing string in French locale throws the following error "comparison of String with 0 failed"

### ISSUE THREAD

**Issue by Dmitri-Filatov** [svenfuchs/rails-i18n#1064]
There should be some error handling and type check that throws meaningful error message when passed argument is of a wrong type. 
Other locales like German or English do not throw error messages due to the Ruby handling equality comparisons ("1" == 1 -> false). As opposed to "2" > 1 -> "comparison of String with 1 failed (ArgumentError)"
This is inconsistent behavior
Judging from the unit tests, you only test "happy paths", there is no error cases testing.

**Comment by pama** [comment]
Hello @Dmitri-Filatov could you provide an example?

**Comment by Dmitri-Filatov** [comment]
> Hello @Dmitri-Filatov could you provide an example?

irb(main):004:0> I18n.default_locale
=> :en
irb(main):005:0> I18n.default_locale = :fr
=> :fr
irb(main):006:0> I18n.t('key1.key2.key3', count: 'abc')
Traceback (most recent call last):
    1: from (irb):6
ArgumentError (comparison of String with 0 failed)
irb(main):007:0> I18n.t('key1.key2.key3', count: '1')
Traceback (most recent call last):
    2: from (irb):6
    1: from (irb):7:in `rescue in irb_binding'
ArgumentError (comparison of String with 0 failed)
irb(main):008:0> I18n.t('key1.key2.key3', count: 1)
=> "1 jour"

**Comment by sunny** [comment]
Here’s a better test with the actual key that seems to be an issue:

```rb
I18n.t("datetime.distance_in_words.x_days", count: "abc")
# => "abc days"
I18n.t("datetime.distance_in_words.x_days", count: "abc", locale: :fr)
ArgumentError: comparison of String with 0 failed
from /Users/sunny/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rails-i18n-7.0.6/lib/rails_i18n/common_pluralizations/one_upto_two_other.rb:7:in `>='
```

**Comment by Dmitri-Filatov** [comment]
@pama You are still not handling the case when a passed string is not a number. This will result in the run time error.
"abc".to_d -> 
/usr/share/ruby/bigdecimal/util.rb:61:in `to_d': undefined method `BigDecimal' for "2.2":String (NoMethodError)
	from main.rb:9:in `<main>'

**Comment by sunny** [comment]
@Dmitri-Filatov I’m not getting the same exception here, see #1067 

Any idea what could be different? Could you provide a test-case to reproduce this?

**Comment by Dmitri-Filatov** [comment]
@sunny Sorry, I was accidentally using old version of Ruby (2.4). This behavior has been fixed since then.
One more comment: "abc".to_d will produce 0, maybe it should be "other" rather than zero?

**Comment by sunny** [comment]
You’re right, that sounds a bit more consistent. Perhaps instead of trying to transform them into numbers (nil included) we should treat any non-numeric as `:other` to cover all cases.
