### ISSUE TITLE
Translation of strings ending in `.`

### ISSUE THREAD

**Issue by LucaProvencal** [svenfuchs/rails-i18n#1068]
## What I tried to do
en.yml:

```
en:
  key:
    foo: "bar"
    baz: "qux"
```

Try to translate the string `key.`

`result = I18n.t("key.")`

## What I expected to happen

`result = ""` or `result = nil`

## What actually happened

```
result = {
  foo: "bar",
  baz: "qux",
}
```

Dependency versions
```
gem "i18n-active_record", "~> 1.1.0", require: "i18n/active_record"
gem "rails-i18n", "~> 7.0.3"

Rails 7.0.4.1
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin20]
```

I believe this is unexpected behavior, but perhaps it is by design. Anyway for the gem to sometimes return a hash and other times a string threw me off a little. It happened as a result translating a variable string i.e. `"key.#{var}"`. We fixed it in our app but I wonder if it should be implemented on the gem level. I'll continue to investigate too. Thank you!

**Comment by codealchemy** [comment]
This is more an issue with `i18n` than `rails-i18n`, see for additional context https://github.com/ruby-i18n/i18n/issues/615

**Comment by LucaProvencal** [comment]
> This is more an issue with `i18n` than `rails-i18n`, see for additional context [ruby-i18n/i18n#615](https://github.com/ruby-i18n/i18n/issues/615)

Understood, thanks. It's probably a duplicate of the issue you linked in that case
