### ISSUE TITLE
Transliteration of all-caps strings

### ISSUE THREAD

**Issue by padde** [svenfuchs/rails-i18n#1102]
I just noticed an edge case for transliteration of capital letters in general. There is no handling of all-caps situations. Consider the following German examples:

```
# capital sharp s only appears in all-caps so not a problem
I18n.transliterate("FUẞBALL")
#=> "FUSSBALL"

# umlauts currently handled only at beginning of a normally spelled noun correctly
I18n.transliterate("Ästhetik")
#=> "Aesthetik"

# however for all caps words it does produce a mixed case result:
I18n.transliterate("KANÜLE")
#=> "KANUeLE"
```

Of course there are more edge cases, like how do we handle single letter strings (I suggest they are basically also all caps, so should produce all caps transliterated).

Any thoughts on this? Should I dive into an implementation of this? Is this a general problem with all languages that needs more careful consideration?

**Comment by pama** [comment]
Hi @padde, the transliterate function is part of the [Ruby i18n](https://github.com/ruby-i18n/i18n) gem. I recommend opening an issue directly in their repository.

**Comment by padde** [comment]
@pama thanks, of course you are right!
