### ISSUE TITLE
Internationalize boolean values

### ISSUE THREAD

**Issue by pisaruk** [svenfuchs/rails-i18n#144]
How do I internationalize boolean values like true and false in active_record?
Inserting: true: "Sim"
                false: "Não"
does not work when displaying the value of some boolean field.

Thanks

**Comment by ramonwiller** [comment]
<%= t("namespace.#{object.boolean_variable.to_s}") %>

pt-BR:
  namespace:
    'true': "Verdadeiro"
    'false': "Falso"
