### ISSUE TITLE
Locales are case sensitive

### ISSUE THREAD

**Issue by DanielHeath** [svenfuchs/rails-i18n#282]
If you set locale to (for instance) 'DE', rails won't find the 'de.yml' config file.

Given that (iirc) the RFC for locale strings calls for case insensitivity, should setting 'DE' find the german strings?

**Comment by bigloser** [comment]
Is this really the case @tigrish?

> 2.1.1.  Formatting of Language Tags
> 
>    At all times, language tags and their subtags, including private use
>    and extensions, are to be treated as case insensitive: there exist
>    conventions for the capitalization of some of the subtags, but these
>    MUST NOT be taken to carry meaning.
> 
>   Thus, the tag "mn-Cyrl-MN" is not distinct from "MN-cYRL-mn" or "mN-
>   cYrL-Mn" (or any other combination), and each of these variations
>   conveys the same meaning: Mongolian written in the Cyrillic script as
>   used in Mongolia.

Also when I check in java.util.Locale and com.ibm.icu.util.ULocale both treat them as case insensitive:

```
ULocale.forLanguageTag("zh-tw").toString() == "zh_TW";
ULocale.forLanguageTag("zh-TW").toString() == "zh_TW";
```
```
Locale.forLanguageTag("zh-tw").toString() == "zh_TW";
Locale.forLanguageTag("zh-TW").toString() == "zh_TW";
```

**Comment by partydrone** [comment]
Case sensitivity causes problems when checking the `Accept-Language` request header for the locale, because some (if not all) browsers report the locale string in all lower case. So in order to set the Rails locale, I have to do some string manipulation to `upcase` the country code portion to get it to work right.

**Comment by tilo** [comment]
@kuroda the two last comments seem to make a case for handling the locale as not being case sensitive

**Comment by nbibler** [comment]
From [BCP 47](https://tools.ietf.org/html/bcp47#section-2.1.1) (referenced in @partydrone's comment above):

> An implementation can reproduce this format without accessing the registry as follows.  All subtags, including extension and private use subtags, use lowercase letters with two exceptions: two-letter and four-letter subtags that neither appear at the start of the tag nor occur after singletons.  Such two-letter subtags are all uppercase (as in the tags "en-CA-x-ca" or "sgn-BE-FR") and four-letter subtags are titlecase (as in the tag "az-Latn-x-latn").

That seems really convoluted to me. Perhaps I18n should provide some type of normalization step when locales are loaded and then use that same normalization whenever strings are requested to be read out of it. Functionally, a normalization step would make it case-insensitive (depending on the implementation of the normalizer) but keep the details of that internal to the library and not require integration changes.

Or, perhaps I18n can simply provide a public method which returns a normalized locale identifier given one (`I18n.locale_for('en-us') #=> :"en-US"`). This approach would require integrators to normalize whatever identifier they'd like to use at the time they use it, if they decided to do so at all. If not, behavior would remain the same as it is today.

From what I see in BCP 47, the capitalization is RECOMMENDED to make it easier for users (people) to recognize. There is no identification that I can find citing that these language identifiers are case-sensitive for machine comparison purposes.

**Comment by justinpaulson** [comment]
7 years later, this is still an issue. The spec seems to be case-insensitive, why is rails-i18n case-sensitive?

"At all times, language tags and their subtags, including private use
   and extensions, are to be treated as case insensitive"

Seems pretty cut and dry.

**Comment by correlator** [comment]
Does anyone have a workaround for this?

**Comment by codealchemy** [comment]
> Does anyone have a workaround for this?

Not sure if this would work for most use cases - but [fallbacks](https://github.com/ruby-i18n/i18n/wiki/Fallbacks) _could_ be used as a workaround

```ruby
irb(main):001:0> require 'i18n'
=> true
irb(main):002:0> I18n.enforce_available_locales = false # Needed to avoid raising an `I18n::InvalidLocale` exception when passing locales that don't match what's 'available' in the i18n backend.
=> false
irb(main):003:0> I18n.backend.store_translations(:en, example: "a")
=> {:example=>"a"}
irb(main):004:0> I18n.t(:example)
=> "a"
irb(main):005:0> I18n.t(:example, locale: 'EN')
=> "translation missing: EN.example"
irb(main):006:0> I18n.backend.class.include(I18n::Backend::Fallbacks)
=> I18n::Backend::Simple
irb(main):007:0> I18n.fallbacks[:EN] = [:en]
=> [:en]
irb(main):008:0> I18n.t(:example, locale: 'EN')
=> "a"
```

Also it seems this is not `rails-i18n` specific, as it's caused by how `i18n` backends (using `Simple` as the example here) [store](https://github.com/ruby-i18n/i18n/blob/f19ee0de1320671856dbc4375ab3f2716d13f03a/lib/i18n/backend/simple.rb#L35-L46) and [fetch](https://github.com/ruby-i18n/i18n/blob/f19ee0de1320671856dbc4375ab3f2716d13f03a/lib/i18n/backend/simple.rb#L84-L104) translations in general - might be worth moving the conversation there?

**Comment by pama** [comment]
This issue is not related to this gem. You can see it yourself creating a new Rails 8 project:

```
i18n-locale-case-sensitive(dev)> I18n.locale = :en
=> :en
i18n-locale-case-sensitive(dev)> I18n.locale = "EN"
(i18n-locale-case-sensitive):5:in '<main>': "EN" is not a valid locale (I18n::InvalidLocale)

        raise I18n::InvalidLocale.new(locale) if !locale_available?(locale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
i18n-locale-case-sensitive(dev)> I18n.locale = "En"
(i18n-locale-case-sensitive):6:in '<main>': "En" is not a valid locale (I18n::InvalidLocale)

        raise I18n::InvalidLocale.new(locale) if !locale_available?(locale)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Please start a discussion at https://discuss.rubyonrails.org or https://github.com/ruby-i18n/i18n
