### ISSUE TITLE
Polish long date format translation with grammatical cases

### ISSUE THREAD

**Issue by Holek** [svenfuchs/rails-i18n#284]
In Polish, proper long date format is `%d %B %Y`, which I [changed](http://www.localeapp.com/projects/370/translations/204105?in_locale=1540) in Localeapp.

The problem occurs with [`date.month_names`](http://www.localeapp.com/projects/370/translations/204107?in_locale=1540), where i18n-rails takes month names, which are translated (correctly) in nominative case (e.g. "styczeń", "luty", etc.).

Proper case for long date formats in Polish is to use genitive case (e.g. "stycznia", "lutego", etc.)

For example, instead of "12 styczeń 2010" it should be "12 stycznia 2010".

What I would propose is another translation, for example: `date.long_month_names`, which would have corresponding names for long month name translations.

We could get around a grammatical case issue and also allow other languages to follow this convention.

**Comment by digitalfrost** [comment]
This is a stale ticket.
@Holek can this be closed?

**Comment by Holek** [comment]
As it is, I guess so. Closing.

**Comment by renatodeleao** [comment]
Sry for reviving this old thread, I had a similar issue with greek (reported on #1106). Is there an intention of adding a way to handle this variations internally as suggestion by OP or was accepted that we always need to add the config file workarounds for each language?

(it's fine if it is, could be mentioned in the README though)
