### ISSUE TITLE
Proposal for a new versioning policy

### ISSUE THREAD

**Issue by kuroda** [svenfuchs/rails-i18n#288]
I think we should maintain two separate gems for Rails 3 and Rails 4, because the latter introduces a few new features that have impact on our repository, such as:

* https://github.com/rails/rails/commit/d72a07f
* https://github.com/rails/rails/commit/ac6941f
* https://github.com/rails/rails/commit/fcc534e

We can pull the first and second one into current master, but the third one will cause some problems for Rails 3.x applications. And, I want to keep the list of *complete* locales for Rails 3 and Rails 4 separately.

Then, what versioning policy should we follow?

I propose that we use `3.2.x` for Rails 3.2 and `4.0.x` for Rails 4.0. How do you think about it?

**Comment by digitalfrost** [comment]
Can be closed?
