### ISSUE TITLE
ISO-639-2 locales are not loaded

### ISSUE THREAD

**Issue by tomeric** [svenfuchs/rails-i18n#297]
We're working on a site that needs the Latin alphabet version of the Serbian locale (scr). This  locale, together with a number of other ISO-639-2 locales have been moved to a different directory 4 months ago (See: 4fb32b918c0e227c5783cb4bc11642a6d4cae20e).

Unfortunately, this means that the locale is never loaded, [the pattern generated](https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/railtie.rb#L24) during initialisation only loads files that are in the root of the `locale` directory.

There are 2 solutions for this problem:
1. Move the ISO-639-2 locales back into the `locale` directory
2. Change the pattern to include files in subdirectories

I'm willing to provide a pull request, but I'd like to know the direction I should choose as I do not know the reason these locales are in their special directory in the first place.

**Comment by digitalfrost** [comment]
Closing as ISO-639-2 locales have been moved back into the locale directory
