### ISSUE TITLE
Numbers as translation keys

### ISSUE THREAD

**Issue by sandstrom** [svenfuchs/rails-i18n#36]
Would be neat if this worked. Ran into it setting up translations for different error pages (404, 500 etc.)

```
>> I18n.t "test"
=> {100=>"dont work", :hundred=>"works"}
>> I18n.t "test.100"
=> "translation missing: sv, test, 100"
>> I18n.t "test.hundred"
=> "works"
```

**Comment by blklane** [comment]
thanks @rathgar!

**Comment by 12finger** [comment]
for anyone looking into using this stuff with a React.js frontend ... use the String version of it:
```yml
en:
  http:
    error:
      "404": Not found.
      ...
```
