### ISSUE TITLE
Adding a distance_of_time_in_words_to_now that works with an appended "ago" in multiple languages

### ISSUE THREAD

**Issue by DaniG2k** [svenfuchs/rails-i18n#373]
Using distance_of_time_in_words_to_now with an appended "ago" translation at the end doesn't work for every language. In english "About a minute ago" is fine but in Japanese, "１分以内　前" is incorrect. I've solved this with the following code, but I think it would be really nice if this were included by default in the rails i18n project.

https://gist.github.com/DaniG2k/6535624

Cheers!

**Comment by digitalfrost** [comment]
Gist referenced above is no longer available.
