### ISSUE TITLE
Include locale name in YAML files

### ISSUE THREAD

**Issue by k1w1** [svenfuchs/rails-i18n#391]
I want to create a select box to allow the user to choose their locale. The challenge is to find a list of all of the locale names, ideally translated into the locale language. Is there a reason why the locale names are not already included, as suggested in this thread: https://groups.google.com/d/topic/rails-i18n/cFbxHcOVfnA/discussion

As long as the locale name is only provided in that locale then this shouldn't be difficult. As a user, if I want to switch to Japanese then presumably I can ready the word "Japanese" in Japanese.

Would you accept a pull request that included locale names? e.g. as i18n.language.name?

**Comment by viktorsmari** [comment]
Is it possible today to get the name from the locale?

Example: the users selects `:"es-MX"` from a `select` dropdown and you want to display the language name?

**Comment by k1w1** [comment]
It has been a while now. We ended up creating custom local files that include the locale name for each locale we support, e.g.

    ja:
      i18n:
        language:
          name: 日本語

**Comment by viktorsmari** [comment]
> It has been a while now. We ended up creating custom local files that include the locale name for each locale we support, e.g.
> 
> ```
> ja:
>   i18n:
>     language:
>       name: 日本語
> ```

Can you share how you get these values in a select box @k1w1 ?

**Comment by k1w1** [comment]
This is the basic idea:

```ruby
module I18n
  def self.name_for_locale(locale)
    I18n.t("i18n.language.name", locale: locale, raise: true, fallback: false)
  rescue I18n::MissingTranslationData
    nil
  end
end

def options_for_locale
  locales = I18n.available_locales.sort.collect { |l| [I18n.name_for_locale(l), l] }.reject { |l| l[0].nil? }
  locales.unshift(["Use browser setting", nil])
end

<%= f.select :locale, options_for_locale %>
```

Which gives:

<img width="252" alt="Screen Shot 2020-04-19 at 7 53 12 AM" src="https://user-images.githubusercontent.com/161640/79691183-ec145880-8212-11ea-87e3-b3ab12d1ec31.png">
