### ISSUE TITLE
date formats break in chinese

### ISSUE THREAD

**Issue by kassi** [svenfuchs/rails-i18n#410]
I tried switching the language to zh when using a standard date format (short).
This breaks with: `translation missing: zh.date.formats.short):`

Is it done intentionally that there's no zh.yml, but only zh-*.yml? We just define chinese to be zh, like all other languages, too.

**Comment by digitalfrost** [comment]
Closing as stale.

**Comment by pjg** [comment]
We're having the same issue as the poster, i.e. our locale is just `zh` (not `zh-CN`) and as such I need to defined custom fallback from `zh-CN` for it to work.

Why is there `es.yml` and ten other `es-XX.yml` variants, but there's no `zh.yml`?
