### ISSUE TITLE
Returns all Keys and values when a blank string of array is passed and returns first value of array when a array of translation is passed.

### ISSUE THREAD

**Issue by santosh-1987** [svenfuchs/rails-i18n#428]
Hi Team ,

I am trying to pass a array with a empty string and I get all key value pairs .
e.g:
[1] pry(#<AgustaController>)> I18n.t([""],:scope => "agusta.errors")
=> [{:"No Stock -  Warehouse to check for stock: 306, 245"=>
   "No Stock - Warehouse to check for stock: 306, 245",
  :"No Stock - Warehouse to check for stock: BLMT, 306"=>
   "No Stock - Warehouse to check for stock: 306, 245",
  :"No Order Request Found !"=>"No Order Request Found !",
  :"Kit Component(s)is mandatory"=>"Kit Component(s)is mandatory",
  :"Requested part is not available in your on site FSL."=>
   "Requested part is not available in your on site FSL. Process stock request anyway ?",
  :"Requested part is not available in your on site FSL"=>
   "Requested part is not available in your on site FSL. Process stock request anyway ?"}]

and One More Issue:

 I18n.t(["3","4"],:scope => "agusta.errors",:default=> [5,4])
=> [5, 5]

Hopefully It Should Return [5,4]
as there is no transaltion for "3" & "4"

**Comment by digitalfrost** [comment]
@santosh-1987 - can this ticket be closed?
