### ISSUE TITLE
Tag marker for delimiters

### ISSUE THREAD

**Issue by dukha** [svenfuchs/rails-i18n#439]
I don't understand why a tag is used before all (most?) delimiters
e.g. The ! before the quoted delimiter ',' below
- en:
    - number:
          - currency:
            - format:
              - delimiter: ! ','

Could someone enlighten me as to what is being achieved here with the exclamation?

**Comment by digitalfrost** [comment]
The exclamation marks were removed in #523 Remove exclamation marks .
