### ISSUE TITLE
Encoding::UndefinedConversionError on rails/transliteration/uk.rb

### ISSUE THREAD

**Issue by bbozo** [svenfuchs/rails-i18n#453]
Hi all :) 

I get this stack trace: https://gist.github.com/bbozo/ca92ec78407761bb8da0 when starting rails app using `rails-i18n` version 3.0.1, `rails` version 3.2.16 and `ruby 1.9.3p484`

Problem seems to be in `rails/transliteration/uk.rb` judging by the debug trace I put into i18n-0.6.9/lib/i18n/backend/base.rb:177:

``` ruby
        # Loads a plain Ruby translations file. eval'ing the file must yield
        # a Hash containing translation data with locales as toplevel keys.
        def load_rb(filename)
          puts filename
          eval(IO.read(filename), binding, filename)
        end
```

A temporary fix is to explicitly specify available locales in the environments,

please let me know if I can be of assistance with additional debug data,

Kind regards

**Comment by digitalfrost** [comment]
@bbozo 
Is this still a problem for you?
Are you still on rails 3.X ? Did you try upgrading to rails-i18n version 3.0.2?

Can this ticket be closed?

**Comment by bbozo** [comment]
I don't even remember posting this :)

**Comment by bbozo** [comment]
Ah yeah, kicked my head again into this one again :-P reinvented the fix, my fix was to explicitly set the locales I'm using in the app, in the developer's `config/environments/*.rb`

For example

``` ruby
config.i18n.available_locales = [:en, :es, :hr]
```
