### ISSUE TITLE
Wrong ActiveRecord scope for errors

### ISSUE THREAD

**Issue by ferblape** [svenfuchs/rails-i18n#518]
Using this gem together with [dynamic_form](https://github.com/joelmoss/dynamic_form) I've realized that the scope for error messages is incorrect in the YAML files, because it should be `:activerecord > :errors > :template` (see [this line](https://github.com/joelmoss/dynamic_form/blob/master/lib/action_view/helpers/dynamic_form.rb#L215)) instead of `:errors > :template` (see the [en.yml](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml#L98) file).

I have checked my hypothesis in [this commit](https://github.com/ferblape/rails-i18n/commit/e34968b498408a92091208cf621dcb4c4b262c4f). If you think it's an error I can send a PR updating the rest of YML files.

**Comment by digitalfrost** [comment]
The errors.format and errors.messages should not be prefixed with activerecord.

These keys are defined in the Active Model without prefix.

Please see https://github.com/rails/rails/blob/v5.0.0.beta2/activemodel/lib/active_model/locale/en.yml

See: #632
