### ISSUE TITLE
Inssue translating the word "on" in pt-BR.yml

### ISSUE THREAD

**Issue by brunowff** [svenfuchs/rails-i18n#528]
We found an inssue translating de word "on" inside a yml file.

When we translate every other word it work normaly.

Please see this question on stackoverflow:

https://pt.stackoverflow.com/questions/53390/porque-o-caminho-da-tradu%C3%A7%C3%A3o-n%C3%A3o-est%C3%A1-sendo-achado#_=_

**Comment by kuroda** [comment]
@brunowff You should post this issue on [i18n](https://github.com/svenfuchs/i18n), not on `rails-i18n`.
