### ISSUE TITLE
Typo in en.yml locale

### ISSUE THREAD

**Issue by marcinbiegun** [svenfuchs/rails-i18n#539]
All english plurals are defined correctly ("one" and "other" forms) except this one: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml#L122

is:

```
        many: Cannot delete record because dependent %{record} exist
```

should be:

```
        other: Cannot delete record because dependent %{record} exist
```

**Comment by kuroda** [comment]
@marcinbiegun Thanks for your suggestion!

Actually, we just took data from https://github.com/rails/rails/blob/master/activerecord/lib/active_record/locale/en.yml.

You are advised to send a pull request to the `rails/rails` repository.

**Comment by marcinbiegun** [comment]
@kuroda I'll fill the request there. Thanks for a fast reply!

**Comment by kuroda** [comment]
@marcinbiegun After they accept your pull request, please send us another one!
