### ISSUE TITLE
Contradicting Test tasks (locales:incomplete and i18n-tasks missing)

### ISSUE THREAD

**Issue by wpp** [svenfuchs/rails-i18n#546]
While submitting https://github.com/svenfuchs/rails-i18n/pull/545

I noticed that the [test tasks in the README](https://github.com/svenfuchs/rails-i18n#test-your-locale-file)
were returning contradicting results:

```
thor locales:incomplete
[...de, de-AT, de-CH, ...]

i18n-tasks missing de
Missing translations (0) | i18n-tasks v0.3.9
Good job! No translations missing!
```

Seems like `i18n-tasks missing de` is not picking up nested keys?

**Comment by wpp** [comment]
Close in fav of #577

**Comment by kuroda** [comment]
Thank you for reminding me about this problem.
