### ISSUE TITLE
Shouldn't PT days of the week include "-feira"?

### ISSUE THREAD

**Issue by hernan124** [svenfuchs/rails-i18n#547]
I barely speak Portuguese but I believe the days from Segunda to Sexta should include "-feira" at the end, as in Segunda-feira.

A native speaker translator translated some text for me including days and did it that way. Besides everything I found online confirms that. For example: http://pt.wikipedia.org/wiki/Dias_da_semana

**Comment by kuroda** [comment]
@hernan124 

Thanks for your suggestion. Could you send us a pull request? I will merge it as soon as possible.

If you are not familiar with `git`, I can help you.

**Comment by hernan124** [comment]
Sure, I wasn't really certain so I asked first in case someone else knew better.

**Comment by hernan124** [comment]
I guess I should have closed this with #548
