### ISSUE TITLE
can i use multi files manage one scope?

### ISSUE THREAD

**Issue by geminiyellow** [svenfuchs/rails-i18n#553]
hello everyone.
look, if i have a i18n resources file like this

    page:
        a:
            title:
        b:
            title:

and i want to split it to multi file like this:

    /page
        /a
           en:
               title:

        /b
            en:
                title:

what can i do?

**Comment by digitalfrost** [comment]
I am sorry your question is not clear to me. Could you please elaborate?

**Comment by digitalfrost** [comment]
@geminiyellow - did not clarify his question. Ticket now stale. Closing.
