### ISSUE TITLE
Missing default countries identifiers

### ISSUE THREAD

**Issue by brauliobo** [svenfuchs/rails-i18n#560]
Identifiers like `fr-FR`, `it-IT`, `ru-RU` and others are missing on the translations. For example, `fr`, `it` and `ru` are part of the two letter spec and may not be used by applications.

Maybe the problem is that two specifications are used. I would stick with the country spec.

An easy fallback would be to used YAML reference, for example:

``` yml
fr: &fr
....

fr-FR:
  <<: *fr
```

If this is ok I can send a PR.

**Comment by kuroda** [comment]
:+1:
