### ISSUE TITLE
Create labels to tag issues relating to rails-3-x and rails-2-3 branch

### ISSUE THREAD

**Issue by digitalfrost** [svenfuchs/rails-i18n#578]
The following Issues labels would be useful

- __rails-2-3__ or __branch-rails-2-3__
- __rails-3-x__ or __branch-rails-3-x__ (personally I think branch-rails-3-x is perhaps clearer)

So that issues like for example #453 could be labelled __rails-3-x__

@kuroda are you ok to create the labels ?

**Comment by kuroda** [comment]
@digitalfrost 

Are you interested to become a member of this repository? If so, I will recommend you to the owner.

**Comment by kuroda** [comment]
Labels have been created.

**Comment by digitalfrost** [comment]
Hi Tsutomu,

Sorry for the delay in replying. Yes I would be interested in becoming a
member of the repo.

Yours,

Gerald

**Comment by kuroda** [comment]
@digitalfrost Great!

**Comment by kuroda** [comment]
Hi @digitalfrost 

Now, you are a collaborator of this repo.
