### ISSUE TITLE
{{count}} no longer resolved in Rails4

### ISSUE THREAD

**Issue by pandar1** [svenfuchs/rails-i18n#604]
In error messages linked to validations like
too_long: "is too long (maximum is {{count}} characters)" 
the {{count}} is no longer resolved to the maximum set in the rule like
validates_size_of :longdescription , :maximum => 1500, :allow_nil => true

in rails 4... in a previous version it worked but I'm not sure from which version it stopped working...

**Comment by jlduran** [comment]
What about `%{count}`?

```yaml
too_long: "is too long (maximum is %{count} characters)"
```

**Comment by pandar1** [comment]
%{count} was resolved to the number of chars allowed, not anymore

**Comment by digitalfrost** [comment]
This issue has been  marked as stale because it has not hadrecent activity. It will be closed if no further activity occurs. Thank you for your contributions.
