### ISSUE TITLE
Missing Spec for Swahili Pluralization

### ISSUE THREAD

**Issue by digitalfrost** [svenfuchs/rails-i18n#620]
In **spec/unit/pluralization_spec.rb** there is no spec describing Swahili pluralization even though there is a Swahili pluralization rule in **/rails/pluralization/sw.rb**

**Comment by kuroda** [comment]
**spec/unit/pluralization_spec.rb** was introduced by @nashbridges in 2012 (392c65fb1f086d1b5708e4be0301d500deb884cc) for _non-English-like_ locales.

The pluralization system of Swahili is same as English. So we don't have a spec for it.

**Comment by digitalfrost** [comment]
I came across this whilst looking at why the tests for #563 failed.

#563 changes the pluralization rule for Turkish to RailsI18n::Pluralization::OneOther. the same as Swahili and I was looking for an example Spec that corresponded to this to see how the failing Spec corresponding to #563 could be corrected
