### ISSUE TITLE
Custom fallbacks not working on production

### ISSUE THREAD

**Issue by elbarto132** [svenfuchs/rails-i18n#654]
Actually that's more a problem about the Rails standard configs, but whoever has this problem is more likely to find it here:
In the standard rails production.rb you will have: config.i18n.fallbacks = true
So if you define custom fallback in application.rb like config.i18n.fallbacks = {en: :de} or whatever, it will be overriden by the setting in production.rb
So after deploying you will be wondering why it's working in development (the .rb file doesn't include this line) but not in production

**Comment by digitalfrost** [comment]
@elbarto132 do you think this should be mentioned in the README ?

**Comment by EGrozdev** [comment]
Oh, Man! Thank you... I was trying to solve this issue couple days and finally I got fix it after your commment. THANK YOU

So, just by changing 
config.i18n.fallbacks = true
with this
config.i18n.fallbacks = {:en => [:en, :de], :de => [:de, :en]}
fallbacks finally work in production as well :)

**Comment by johnnyshields** [comment]
This issue can be closed
