### ISSUE TITLE
.be contains Belarus translations, whereas it should be .by

### ISSUE THREAD

**Issue by Marahin** [svenfuchs/rails-i18n#666]
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/be.yml contains Belarus translations (at least I suppose so - I have thrown it through Google translate and it confirmed my thoughts), but '.be' TLD (and :be symbol in Rails) is supposed to handle Belgium translations. 

Also, Belarus has '.by' TLD and I suppose it should be named by.yml too, to keep it standardized?

**Comment by yaroslav** [comment]
Not really. Locale names and domain names are different and follow different specifications. For instance, `uk` is for Ukraine.

Related: https://www.google.ru/search?q=belarus+locale

Overall, it is named in a proper way.
