### ISSUE TITLE
wrong/outdated key?

### ISSUE THREAD

**Issue by webzorg** [svenfuchs/rails-i18n#684]
Hello, I am missing a translation for this key. `errors.messages.not_saved.one`, or pretty much many other keys if this is applies to other keys. in the rails-i18n gem though, same text of `1 error prohibited this %{model} from being saved` is saved under `errors.template.header.one`. is the rails-i18n yml tree outdated or what am I missing? Thank you in advance.

**Comment by digitalfrost** [comment]
What language are you experiencing a problem with?

**Comment by webzorg** [comment]
Georgian, I translated whole yml file using a default english file, long time has passed since then though so I don't remember all the details. :)

**Comment by digitalfrost** [comment]
Can I close the ticket as stale?
