### ISSUE TITLE
cs file:  x_minutes

### ISSUE THREAD

**Issue by abigailes** [svenfuchs/rails-i18n#687]
Hello

We received a report from our translators that the translation for minutes used in the cs (Czech) file is incorrect. Currently the translation is the following:

      x_minutes:
        one: minutou
        few: "%{count} minutami"
        other: "%{count} minutami"

Our translators are saying it should always be "min"

So:

one: min
        few: "%{count} min"
        other: "%{count} min"

**Comment by gorn** [comment]
I am native Czech speaker and I thing that needs some explanation. The original translation is fine as far as it is ONLY used in context like `"Before #{t :x_minutes, count: count}"`. It MIGHT be wrong if used in another context. The suggestion avoids this problem by using abbreviation "min" which is not conjugated. However if the only place the translation is used is in the mentioned context, than the current translation sounds better.

**Comment by digitalfrost** [comment]
@gorn Thank you for your input.
What would you do keep as is or change to the abbreviation?  
@Mart17 Do you have an opinion?
