### ISSUE TITLE
Why isn't 'back' in the gem?

### ISSUE THREAD

**Issue by bertBruynooghe** [svenfuchs/rails-i18n#691]
I often come across situations were I thought: why is this thing not available in rails-i18n since it is so common, but most of the times, I think there is good reason why it isn't there.

One of this situations is the 'ok' and 'cancel' button, and after looking how scaffolds do it, I think you can replace 'ok' most of the times with a proper key from the `helpers.submit` category, which is usability-wise better. But for the 'back' button (which boils down to the same as 'cancel'), scaffolding keeps hardcoding 'Back' there. Since it is in the scaffolds, shouldn't it be in rails-i18n instead?

**Comment by pama** [comment]
rails-18n is responsible for translating the locale files present in the Ruby on Rails source code. [ruby-core](https://discuss.rubyonrails.org/c/rubyonrails-core/5) is the right place to discuss that. Thanks.
