### ISSUE TITLE
Hungarian should be OneOther, not Other

### ISSUE THREAD

**Issue by jfly** [svenfuchs/rails-i18n#706]
See https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/hu.rb, which defines Hungarian as "Other".

(for the record, I do not speak Hungarian, but some members of our organization do, and they assure us this is wrong)

For example, the following 2 English sentences *do* translate very similarly in Hungarian:

"registration ends in 5 days"
> A regisztráció lezárul 5 nap múlva.

"registration ends in 1 day"
> A regisztráció lezárul 1 nap múlva.

Note that "nap" is used in both of these, so a translation that just specifies `other:` *would* work here:

```
other: "A regisztráció lezárul %{nap} nap múlva."
```

It appears that `other:` is sufficient any time you're including a cardinal number. However, that's not always the case. For example, the following 2 English sentences get translated in different ways:

"Registration accepted! Email notification sent."
> Regisztráció elfogadva! Értesítés kiküldve e-mailben.

"Registrations accepted! Email notifications sent."
> Regisztrációk elfogadva! Értesítések kiküldve e-mailben.

Here we do use a different form for `one:` than for `other:`, but that's not possible with the current Hungarian pluralization rules defined in this repository.

[Wikipedia does agree with this](https://en.wikipedia.org/wiki/Hungarian_language#Nouns):

> Noun plurals are formed using the suffix –k (az almák ‘the apples’)—however, following a numeral, the singular is used (e.g. két alma ‘two apples’, literally ‘two apple’; not *két almák).

Furthermore, it looks like the [Unicode CLDR specification](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#hu) also agrees that Hungarian should get both `one:` and `other:` keys.

Would you accept a PR that changes Hungarian from `Other` to `OneOther`?

(Here's a link to the relevant issue for our organization: https://github.com/thewca/worldcubeassociation.org/issues/1261#issuecomment-276785466)

**Comment by digitalfrost** [comment]
Sorry for the delay in getting back to you.
Yes we would accept such a pull request.
