### ISSUE TITLE
Rails 5.1.0 support

### ISSUE THREAD

**Issue by skuijper** [svenfuchs/rails-i18n#726]
I don't think we will be able to use the rails-i18n gem with rails 5.1.0 as long as this dependency exists:

`'railties', '~> 5.0'`

Rails 5.1.0 requires `'railties', '= 5.1.0'`

The readme suggests that the master branch should work for Rails 5.x.

Is Rails 5.1.0 support on the radar?

**Comment by kuroda** [comment]
@skuijper 

According to http://guides.rubygems.org/patterns/#pessimistic-version-constraint, the version constraint `~> 5.0` equals to `>= 5.0, < 6.0`.

The `rails-i18n` does support Rails 5.1.

**Comment by skuijper** [comment]
@kuroda you are right. I incorrectly assumed the dependency definition would only allow patches on `5.0`. The problem I was having while updating rails ended up being another gem. Sorry to bother you.

**Comment by kuroda** [comment]
That's OK.

With your pointed out, I modified the README.md.
