### ISSUE TITLE
pl: long date format is invalid

### ISSUE THREAD

**Issue by mspanc** [svenfuchs/rails-i18n#729]
Currently long date format for the pl locale is specified as follows:

 long: "%B %d, %Y"

It produces e.g.

`lipiec 06, 2017 20:11`

it is not natural for polish native speakers.

The right is

6 lipiec 2017, 20:11

(day without leading 0 / month / full year / comma / datetime)

but it is gramatically incorrect, as there are cases in polish and month names should not be in their primary form. Here's the list:

stycznia
lutego
marca
kwietnia
maja
czerwca
lipca
sierpnia
września
października
listopada
grudnia

but that form should be used ONLY in the long format, for rest of the cases month names that are currently present in the locale should remain.

**Comment by kuroda** [comment]
@mspanc Thank you for reporting.

It would be great if you submit a pull request. I will merge it as soon as possible.

**Comment by adas172002** [comment]
Hi,

I would like to point to your attention that there is a gem [polish](https://github.com/grk/polish) that tries to address this special requirement of Polish language. Perhaps a solution applied in this gem can be also used for rails-i18n.

**Comment by digitalfrost** [comment]
Closed by #903
