### ISSUE TITLE
Can someone list what is the locale key for Creole

### ISSUE THREAD

**Issue by bjm88** [svenfuchs/rails-i18n#736]
Specifically haitian Creole b/c there are lots of dialects but really any Creole for starters...

If not there can we just add our own key and put all our own locale translations anyway...sees we get error when trying...

**Comment by acesuares** [comment]
Please contact me or visit papiamentu.info

**Comment by digitalfrost** [comment]
I believe it should be: **ht_HT**

Source: https://lh.2xlibre.net/locale/ht_HT/
