### ISSUE TITLE
Feature Request: Support Filipino

### ISSUE THREAD

**Issue by simonfranzen** [svenfuchs/rails-i18n#759]
I can see that you catch :fil in inflectors, but I cannot find a fil.yml

Does rails-i18n support Filipino ?

**Comment by kuroda** [comment]
No, it does not. I don't know why the `:fil` was added to inflectors.

If you make a pull request, I will merge it as soon as possible.

**Comment by simonfranzen** [comment]
@kuroda OK, thanks for the information. I will make a PR for fil.yml, when we finished the translations for it.

**Comment by kristm** [comment]
@simonfranzen Filipino is supported (tl - tagalog): https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/tl.yml

**Comment by simonfranzen** [comment]
thanks @kristm 

ok, well, didnt know it's TL - are we sure about that ?
@kuroda what about the :fil inflector ?

**Comment by kristm** [comment]
as a native filipino speaker, I'm positive 👍 

filipino is the official name of the Philippines' national language: it's supposed to be a hybrid compromise that would include most of the country's major languages - but in reality, it's mostly just tagalog. most tagalog speakers would use filipino or tagalog to refer to the same language.

more: https://en.wikipedia.org/wiki/Filipino_language#Filipino_vs._Tagalog

**Comment by kuroda** [comment]
@simonfranzen 

Well, I think we should remove `:fil` inflector from this repository.

**Comment by simonfranzen** [comment]
@kuroda Pull Request is open

**Comment by simonfranzen** [comment]
ok, so now it's just in the master branch. How can we provide this easily for rails 4 branch?
