### ISSUE TITLE
Belarus translation (BY) incorrectly saved as Belgium (BE)

### ISSUE THREAD

**Issue by poshmonkey** [svenfuchs/rails-i18n#760]
I was looking for translations for Belgium and noticed that the be.yml file contains Belarusian translations. I believe be.yml should be changed to by.yml.

**Comment by digitalfrost** [comment]
**be** is correct:
Source: https://www.science.co.il/language/Locale-codes.php
This also matches the iso gem: https://github.com/tigrish/iso/blob/master/locales/en.yml
