### ISSUE TITLE
How to escape long unicode character?

### ISSUE THREAD

**Issue by thomasnal** [svenfuchs/rails-i18n#764]
Hi,

I want to insert emoji into strings stored in i18n localization files `config/local/en.yml` including unicode characters longer than 4 bytes.  The question is, is it possible?  If yes, how to do it?

The problem is format `\u{...}` doesn't compile.  Option without curly brackets is not an option because unicode characters longer than 4 bytes gets mangled, not recognized.

```yaml
en:
  my_string: "\u{1F525} hello this fails compilation"
```

```
I18n::InvalidLocaleData:
  can not load translations from /.../config/locales/en.yml: #<Psych::SyntaxError: (/.../config/locales/en.yml): did not find expected hexdecimal number while parsing a quoted scalar at line 314 column 16>
```

Version: Rails 5.0.0.1
Cheers.

**Comment by MathieuDerelle** [comment]
maybe try with this
```
puts "\u{1F525}".to_yaml
--- "\U0001F525"
```
