### ISSUE TITLE
New Chinese pluralization rules break stuff

### ISSUE THREAD

**Issue by JasonBarnabe** [svenfuchs/rails-i18n#767]
I noticed that 5.1.0 has changed the pluralization for Chinese to require a `one` key (#754). The upgraded gem breaks my site as I do not currently have "one" forms for Chinese content.

I'm far from a Chinese expert, but [the CLDR](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html#zh) states there should only be an "other" rule for Chinese pluralization. The translation site I use (Transifex) also follows this guideline.

Would it be possible to make Chinese fall back to "other" if a "one" translation is not available? The actual translations from #754 that caused this change seem to be special cases.

**Comment by kuroda** [comment]
@pinewong 

What is your opinion on this issue? I cannot make a decision for I am not a Chinese speaker.

**Comment by pinewong** [comment]
@JasonBarnabe @kuroda 

In semantic meaning, the "other" and "one other" rule are all ok for Chinese. If CLDR set the specifications that should only be an "other" rule, we should follow it. But the translate file(yaml file) should use the the same rule, then there will be no ambiguaty.

For the wrong result of "Byte" in #754 , we can use Chinese expression to avoid it. I will make a pr for it later.

**Comment by kuroda** [comment]
Just released the version 5.1.1, which fixed this issue.
