### ISSUE TITLE
Belarusian key 'many' missing

### ISSUE THREAD

**Issue by PeterGreenSamanage** [svenfuchs/rails-i18n#772]
Hi,
I'm getting the following error: "translation data {:one=>"1 дзень", :other=>"%{count} дзён"} can not be used with :count => 7. key 'many' is missing."

This happens when i run "time_ago_in_words" function in Belarusian.

I think the datetime: key should have the 'many' and maybe 'few' keys in this language.
Example the current be.yml file: 
datetime:
    distance_in_words:
      about_x_hours:
        one: каля 1 гадзіны
        other: каля %{count} гадзін
      about_x_months:
        one: каля 1 месяца
        other: каля %{count} месяцаў
      about_x_years:
        one: каля 1 года
        other: каля %{count} гадоў

**Comment by Shaglock** [comment]
Yes, you are right. I'll fix that very soon!
