### ISSUE TITLE
Lithuanian: i18n activerecord does not seem to support grammatical cases

### ISSUE THREAD

**Issue by ValdasVabolis** [svenfuchs/rails-i18n#797]
# i18n activerecord does not seem to support grammatical cases

I'm working on an app that supports two languages - English and Lithuanian. Lithuanian language has special grammatical cases for words - a word could be used in a nominative, accusative and similar cases.

Example:

"Tai yra apklausa" ( This is a poll )
"Šią apklausą" ( This poll )

As you can see, the word "apklausa" ( poll ) has different spelling based on the grammatical case.

To solve this problem, I tried adding groups to model locales:

```
	en:
		activerecord:
			models:
				polls:
					accusative:
						one: apklausą
						other: apklausas
					nominative:
						one: apklausa
						other: apklausos
```

Unfortunately, this resulted in a I18n::InvalidPluralizationData error can not be used with :count => 1. key 'one' is missing. It appears that i18n activerecord does not recognize these keywords and gets confused.

I also thought about trying to re-phrase the words, but there isn't a good way to really do it without making it sound very unnatural.

What would be an efficient and appropriate way to handle this without introducing immense complexity to the app?

**Comment by digitalfrost** [comment]
Stale ticket: closing
