### ISSUE TITLE
Should html lang="en" be loaded dynamically?  

### ISSUE THREAD

**Issue by CatPerry** [svenfuchs/rails-i18n#798]
Hey, 
I'm working on regionalizing (en-US and en-AU) an app and found a key change to make the i18n gem work well was to add this to the application.html.erb file

`<html lang=**"<%= I18n.locale %>"** dir="ltr">`

It works well, but is that as intended? If so, maybe add that to the documentation? Thanks! If not, lmk.

**Comment by viktorsmari** [comment]
@CatPerry is it recommended that we do something this? `lang="<%= I18n.locale %>"`
I cannot find anything about it

**Comment by CatPerry** [comment]
I ended up doing that in order to not set a default lang in "en" and instead to do it dynamically, using what's available by the gem. Not sure the syntax is still right anymore,  but that's the logic there. @viktorsmari
