### ISSUE TITLE
Human precision in Swedish locale file is set to 1

### ISSUE THREAD

**Issue by mtthwhggns** [svenfuchs/rails-i18n#838]
Hello,

I'm interested in the reasoning behind the `human` `precision` being set to 1 in the Swedish locales (https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/sv-SE.yml#L176 and https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/sv.yml#L176). 

It leads to some unexpected appearances (152 miljon becomes 200 miljon), when other locales (I've checked mostly the neighbouring regions) tend to use 3 (so 152 million in this example).

After a quick look at the git history, I can't see any discussion about this, or any notes in the commit message about why it was done, so I'm not sure if there's a specific reason.

If there isn't, could we consider changing it to 3? If there is, could we consider adding a comment to the file to avoid further questions like this?

**Comment by soma** [comment]
I am a Native Speaker and would love to help, but I am afraid I don't understand what "human precision being set to 1" is supposed to do. I can't see why it would be useful to round this number like you say. "152 miljoner" is not supposed to be rounded to "200 miljoner" for any very locale-specific cultural norm that is unique to us swedes. :)

**Comment by henrik** [comment]
@soma I believe it's for https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human.

**Comment by henrik** [comment]
As a native Swede, I also can't think of any reason Swedish would differ from e.g. English in this respect.
