### ISSUE TITLE
wrong currency format in ja.yml

### ISSUE THREAD

**Issue by nipe0324** [svenfuchs/rails-i18n#846]
Now, currency format is `"%u%n"` in ja.yml
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml#L152

But, It should be `"%n%u"` as below.

```rb
# format: "%u%n"
> helper.number_to_currency(1000, locale: :ja)
=> "円1,000"

# format: "%n%u"
> helper.number_to_currency(1000, locale: :ja)
=> "1,000円"
```

**Comment by nipe0324** [comment]
I create pr: https://github.com/svenfuchs/rails-i18n/pull/847

**Comment by digitalfrost** [comment]
Fixed by: **fix ja currency format. #851**
