### ISSUE TITLE
Serbian pluralization rules are wrong

### ISSUE THREAD

**Issue by Gargron** [svenfuchs/rails-i18n#853]
According to https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html, the Serbian language has "one", "few" and "other". But this gem uses the "Common East-Slavic" behaviour which adds a "many" key as well.

**Comment by lavaturtle** [comment]
I'm running into this issue as well and would like to see it fixed. Is there a reason it was closed?
