### ISSUE TITLE
Recommendation how to select both locale, and a (separate) currency?

### ISSUE THREAD

**Issue by viktorsmari** [svenfuchs/rails-i18n#874]
We have an app which currently has 5 languages, with more being added slowly.

How can we allow the user to for example use Spanish as a language, but have the currency of Chile, Argentina or Bolivia etc (and not use the Euro)?

It's only used to display a currency, no need to convert between currencies.

We already have `@company.locale` and we could add `@company.currency`.
Then we could do something like: `number_to_currency(price, locale: @company.currency)`

Our problem at the moment is how to **select** the currency **with the country name** in a `<select>`.

This is how we choose between allowed languages `@company.locale`
```ruby
[:en, :de, :is, :fr, :es, :'en-GB'].map do |locale|
  [I18n.t('name', locale: locale), locale.to_s]
end
```

This is how we _could_ choose between all supported currencies `@company.currency` but this **only shows the unit**
```ruby
I18n.available_locales.map do |locale|
  [ I18n.t('number.currency.format.unit', locale: locale),  locale.to_s ]
end
```

How can we also show the country belonging to each currency unit?

I also asked this on [SO](https://stackoverflow.com/questions/58357673/how-to-allow-users-to-select-all-currencies-but-with-limited-languages?noredirect=1#comment103079130_58357673)

**Comment by viktorsmari** [comment]
@kuroda do you have any suggestion on how to do this?

We would like to allow companies in our app to select between all available currencies, without having to manually create a name and a `.yml` file for all of them. The English name should be fine.

**Comment by kuroda** [comment]
Do you want to get an HTML snippet like this?

```html
<select name="locale">
  ...
  <option value="es-CL">Spanish (Chile)</option>
  <option value="es-AR">Spanish (Argentina)</option>
  <option value="es-BO">Spanish (Bolivia)</option>
  ...
</select>
```

**Comment by viktorsmari** [comment]
Yes, but for the currencies.

I might be confused because `i18n` has currency formatting, but not the names for the currencies like 'Australian Dollar' etc.

**Comment by kuroda** [comment]
> Yes, but for the currencies.

Coud you give me an example of the `<select>` snippet that your want to produce?

**Comment by viktorsmari** [comment]
We ended up using the [Money](https://github.com/RubyMoney/money) gem to get the list of currencies, using the
```ruby
Money::Currency.table.values.map {|x| [x[:iso_code], x[:name] ]}
```

```html
<select name="currency">
  ...
  <option value="ISK">Icelandic Króna</option>
  <option value="EUR">EURO</option>
  ...

How did you generate your HTML?
Can that be used for currencies or do we need to use the Money gem?
</select>
```

**Comment by kuroda** [comment]
Well, I don't think you can generate that HTML using only our gem.

You would better to use the `money` gem.

**Comment by viktorsmari** [comment]
Final question, how did you generate your HTML above?

```html
  <option value="es-CL">Spanish (Chile)</option>
  <option value="es-AR">Spanish (Argentina)</option>
```

**Comment by kuroda** [comment]
You are misunderstanding something. I wrote this HTML by hand.

**Comment by viktorsmari** [comment]
I was hoping it could be generated by default, but that is related to the discussion why there is not a `name` or `english_name` in each translation file.

Thanks for your time!
