### ISSUE TITLE
"pt-br" is not a valid locale

### ISSUE THREAD

**Issue by AvivM96** [svenfuchs/rails-i18n#888]
Hey, I'm using rails-i18n with rails 5.2, and we are using the `pt-br` language code which is a valid language code by the ISO 639-1, however the gem is only working with `pt-BR` in uppercase. what should i do to make it support the language code in lowercase ? 

thanks

**Comment by pama** [comment]
@AvivM96 I'm not sure if ISO 639-1 sets more than 2 letters, as I believe the main goal is to represent a language and not their variations. I couldn't find an RFC or similar to clarify. Do you have a document with that?

How are you setting the current locale on your app? I think you will need to handle that yourself, like uppercasing when you set `I18n.locale`

**Comment by AvivM96** [comment]
@pama thanks for the quick reply, I've tried to dig a little bit more, I was wrong because of a misleading website.

for your question my application can receive language code from external resources and sometimes they come in lowercase, it will be nice if there will be an option to make `I18n.locale` to become not case sensitive as to my understanding there is not difference with `pt-br` and `pt-BR`.

**Comment by pama** [comment]
@AvivM96 i iguess you could co some code to uppercase -xx to -XX.

In all references I see to ISO 3166-2, the subdivision codes are uppercased.
