### ISSUE TITLE
Columbian Spanish should use the decimal comma

### ISSUE THREAD

**Issue by alekseyg** [svenfuchs/rails-i18n#890]
A client brought up an issue with currency and numbers being formatted incorrectly in our app when using the es-CO locale. After looking it up, I've confirmed that Columbia uses the comma as the decimal separator and the full stop as the thousands separator. However, the es-CO locale in rails-i18n uses the US format of full stop decimal separator and comma thousands separator.

https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma

**Comment by digitalfrost** [comment]
Closed by #898
