### ISSUE TITLE
Fallback languages per Customer

### ISSUE THREAD

**Issue by c2ofh** [svenfuchs/rails-i18n#906]
Hi,

we have customers which are using different languages.
So there are fields with some default values in all languages, cause when a customer activates another language, the field should not be empty.

Now there is the case: 
The customer has activated english as language and removes a text, because they want to clear the view. 
Now there is a fallback for a language the customer didn't want to use.

Am I able to set the fallback list at runtime?

**Comment by gmonein** [comment]
In top of your application controller you can add something like
```ruby
class ApplicationController
  before_action :set_locale
  before_action :set_locale_fallback

  def set_locale
    I18n.locale = current_user.locale
  end

  def set_locale_fallback
    user_locale = current_user.locale || I18n.default_locale
    user_locales = current_user.translated_things.keys
    I18n.fallbacks[user_locale] = user_locales
  end
end
```

As rails is mono-threaded, this will not impact others users local
ensure that this is executed for every request, as it's a global variable and not changing it can create unconsistent response

**Comment by c2ofh** [comment]
Hey @gmonein 
Thank you very much. I will test it :)
