### ISSUE TITLE
add i18n for time_ago_in_words?

### ISSUE THREAD

**Issue by yshmarov** [svenfuchs/rails-i18n#913]
right now, when using the i18 gem, running something like
`    <%= time_ago_in_words(@user.created_at) %>
`
produces the result
en:
10 minutes 
fr:
10 minutes
es:
10 minutos

however **time_ago** always requires context like 
en:
10 minutes **ago**
fr:
**il y a** 10 minutes
es:
**hace** 10 minutos

So what do you think about adding a helper to i18n?

**Comment by pama** [comment]
@yshmarov, we only handle locale data. `time_ago_in_words` belongs to ActionView, and the right place to start a discussion is here: [rubyonrails-core](https://discuss.rubyonrails.org/c/rubyonrails-core/5).
