### ISSUE TITLE
Inconsistent number precision in Norwegian locales?

### ISSUE THREAD

**Issue by floehopper** [svenfuchs/rails-i18n#915]
I recently noticed that `ActionView::Helpers::NumberHelper#number_to_percentage` is using a precision of 2 in Norwegian locales, but a precision of 3 in other locales:

```ruby
test 'number_to_percentage' do
  I18n.with_locale(:'en-GB') { assert_equal '45.123%', number_to_percentage(45.123) }
  I18n.with_locale(:'cy-GB') { assert_equal '45.123%', number_to_percentage(45.123) }
  I18n.with_locale(:'fr-CA') { assert_equal '45,123%', number_to_percentage(45.123) }
  I18n.with_locale(:'en-CA') { assert_equal '45.123%', number_to_percentage(45.123) }
  I18n.with_locale(:'no-NO') { assert_equal '45,12%', number_to_percentage(45.123) }
end
```

I assume this is something to do with the `number.format.precision` setting in the locale configuration. However, strangely the same thing does not seem to affect `ActionView::Helpers::NumberHelper#number_with_delimiter`:

```ruby
test 'number_with_delimiter' do
  I18n.with_locale(:'en-GB') { assert_equal '9,999.999', number_with_delimiter(9_999.999) }
  I18n.with_locale(:'cy-GB') { assert_equal '9,999.999', number_with_delimiter(9_999.999) }
  I18n.with_locale(:'fr-CA') { assert_equal '9 999,999', number_with_delimiter(9_999.999) }
  I18n.with_locale(:'en-CA') { assert_equal '9,999.999', number_with_delimiter(9_999.999) }
  I18n.with_locale(:'no-NO') { assert_equal '9 999,999', number_with_delimiter(9_999.999) }
end
```

Can anyone tell me whether this is intentional behaviour? The inconsistency seems odd to me, but I don't speak any Norwegian nor do I know anything much about Norwegian culture!

**Comment by floehopper** [comment]
[From a Norwegian speaker](https://twitter.com/aslak_hellesoy/status/1398410583406485504):

> You might find the answer deep down in the ICU spec, on which most i18n libs are based. FWIW I’m used to seeing most percentages formated with two decimal precision - didn’t even know 3 decimals was common.

**Comment by pama** [comment]
The "original" locale file sets it to 3, and probably all other translators used it as a reference. Norwegian locale seems an exception 😀

**Comment by floehopper** [comment]
> The "original" locale file sets it to 3, and probably all other translators used it as a reference. Norwegian locale seems an exception 😀

So it seems as if there are a few questions:

1. Why is the default set to 3?
2. Why is Norwegian an exception?
3. Are there any other locales which should also be exceptions?

**Comment by pama** [comment]
1) I don't know. Maybe you can ask here: [Ruby forums](https://discuss.rubyonrails.org). This repository translates the [active_support/locale/en.yml](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/locale/en.yml) file. 

2) It was the translator's decision.

3) Lickly, but we depend on native speakers' contributions.

**Comment by floehopper** [comment]
Cool. Thanks for explaining. Ultimately I don't really care about this, but I noticed the inconsistency and thought it was worth mentioning in case it was a genuine issue. If you're happy with how it currently is, then I'm happy for you to close this issue.
