### ISSUE TITLE
How to render class/controller specific translations with lazy lookup on a partial in Rails 5.2?

### ISSUE THREAD

**Issue by fchampreux** [svenfuchs/rails-i18n#916]
I use a partial _object_index.html.erb to display the index of various objects.
This partial contains references to column headers such as .Code, .Name ... to support lazy lookup of actual header labels.
So translation files contain the reference to the controller/action who displays the index view. Here is the example for BusinessArea class (de_OFS is a business specific language):
```
# Code for language as declared in i18n configuration
de_OFS:
  # Considered object from controller's methods. In the controller, the relative path for the term is marked by the point (.)
  # Use generic terms, excluding objec name (ie Manage instead of ManageBusinessArea )
  business_areas:
    index:
      # Columns titles
      Code:                                   "Kurzname"
      Name:                                   "Name"
      Description:                            "Beschreibung"
      Owner:                                  "Eigentümer"
      UpdatedBy:                              "aktualisiert von"
      UpdatedAt:                              "aktualisiert am"
```

The issue is that rails fetches the translations from de_OFS.shared.object:index.Name, instead of using the controller/action keys. This implies that the column names will be the same for various objects, which is not the case from the business point of view.

Is there a way to define how the lazy loading resolves the path to the labels?

Thanks a lot!

PS. Dicussion started on [StackOverFlow](https://stackoverflow.com/questions/65009008/how-to-render-class-controller-specific-translations-on-a-partial-in-rails-5-2)

**Comment by sunny** [comment]
Hi Frédéric! I think this is not the correct repository for this issue as `rails-i18n` only contains the locales, but doesn’t handle Rails’ logic on how keys are created.
