### ISSUE TITLE
Activemodel Errors

### ISSUE THREAD

**Issue by 6temes** [svenfuchs/rails-i18n#917]
I am getting this errors in my app:

`translation missing: ja.activemodel.errors.messages.record_invalid`

It seems that the translation in this project is under `ja.activerecord.errors.messages.record_invalid`. Would it make sense to add the activemodel version too?

**Comment by kuroda** [comment]
No. There is no such key in the translation files provided by rails itself.

See:

* https://github.com/rails/rails/blob/master/activerecord/lib/active_record/locale/en.yml
* https://github.com/rails/rails/blob/master/activemodel/lib/active_model/locale/en.yml

**Comment by 6temes** [comment]
Upps, my mistake then. Sorry for the inconvenience.
