### ISSUE TITLE
kargs problem when upgrading to ruby@3

### ISSUE THREAD

**Issue by layerssss** [svenfuchs/rails-i18n#918]
Hi, I'm not sure this would be an issue here or the other gem calling `i18n` (`formtastic`).

The error was: `wrong number of arguments (given 2, expected 0..1)`

in i18n (1.8.7) lib/i18n.rb:195:in `translate':  

```
def translate(key = nil, throw: false, raise: false, locale: nil, **options)
```

This was called from `formtastic`, (formtastic (3.1.5) lib/formtastic/i18n.rb:26:in `translate'):

```
::I18n.translate(key, *(args << options))
```

If I understand this correctly `formtastic` is calling `translate` with the options hash being the second positioned-arg. Which ruby@3 will no longer convert it into keyword-arg. But will `ruby-i18n` still support supplying the options hash as the second positioned-arg? (If not then this issue should be opened in `formtastic` instead)

**Comment by layerssss** [comment]
Bugger me, `formtastic` already has this tracked. https://github.com/formtastic/formtastic/issues/1325  But btw do you think it's a good idea to support both kargs and hash as the second arg for other gems that depends on it?

**Comment by pama** [comment]
@layerssss we only handle locale data here. Your question seems related to formtastic.
