### ISSUE TITLE
ISO-compliant country code: rename UK to UA

### ISSUE THREAD

**Issue by yshmarov** [svenfuchs/rails-i18n#942]
The ISO code for Ukraine is `UA`, not `UK`. 

https://en.wikipedia.org/wiki/ISO_3166-2:UA

Also UK is commonly refered to as United Kingdom...

Can we get this renamed?

https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/uk.yml

**Comment by pama** [comment]
@yshmarov [ISO 3166-2](https://www.iso.org/iso-3166-country-codes.html) exist to define codes for countries and countries subdivisions, and not for their official languages.

I believe we are using ISO 639-1 for languages, and ISO 3166-2 for regions.

As an example, Portugal (PT code - ISO 3166-2) and Brazil (BR code - ISO 3166-2) have the same official language (pt ISO 639-1): pt-PT and pt-BR, respectively. English is another good example.
