### ISSUE TITLE
Spanish Locale Month Names do not begin with a Capital Letter

### ISSUE THREAD

**Issue by nikhithajosh97** [svenfuchs/rails-i18n#944]
The month names for Spanish locale begin with a small letter.

**Comment by jlduran** [comment]
That's how it's supposed to be:

https://www.rae.es/duda-linguistica/los-nombres-de-los-meses-se-escriben-en-mayuscula

**Comment by nikhithajosh** [comment]
Oh... Alright! My project required capital letters and I was wondering why... Thanks!
