### ISSUE TITLE
railties dependency and rails 7 compatibility

### ISSUE THREAD

**Issue by strobilomyces** [svenfuchs/rails-i18n#954]
First, thanks to everyone who works on this gem.

I recently ran into a compatibility issue when running `bundle update` against rails/main (currently at https://github.com/rails/rails/commit/a35a380c2cdc7fe032f927095545aee21a192f54):

```ruby
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails was resolved to 7.1.0.alpha, which depends on
      railties (= 7.1.0.alpha)

    rails-i18n (~> 6.0.0) was resolved to 6.0.0, which depends on
      railties (>= 6.0.0, < 7)
```

Noting that not much has changed between rails-7.0.0rc1 (which bundled fine, obviously) and rails/main, I forked this repo and (naively) changed the dependency in rails-i18n.gemspec from

`s.add_runtime_dependency('railties', '>= 6.0.0', '< 7')`

to

`s.add_runtime_dependency('railties', '>= 6.0.0')`

Everything bundled fine and I didn't notice anything weird with my translations. Obviously I didn't do any extensive testing with the gem itself.

Anyway, in brief, I was curious if there were any known compatibility issues with railties >= 7.0 that would warrant keeping the dependency above or whether a version bump would be appropriate.

Thanks again.

**Comment by uxxman** [comment]
+1 for this since rails 7 is released. Everything works fine on rails 7RC3
