### ISSUE TITLE
Is there anyone who can take over the maintainers of this repository?

### ISSUE THREAD

**Issue by kuroda** [svenfuchs/rails-i18n#960]
For some reason, I'm no longer an active user of Ruby on Rails.

I would be very happy if someone who can take over the maintainer of this repository can run for it.

**Comment by pama** [comment]
I'm available to help.

**Comment by MoskitoHero** [comment]
Willing to help too.

**Comment by kuroda** [comment]
@svenfuchs

Will you consider giving them the necessary permissions to this repository and RubyGems.org?

**Comment by svenfuchs** [comment]
@kuroda, of course I will! 

Your endurance and patience, taking best care of this repository for more than 12 (twelve!) years is nothing but legendary. There are no words to express the respect and gratitude the Rails community owes you for this. 🙇🏻‍♂️

Please let me know if there ever is anything I can do for you!

@pama @MoskitoHero thanks heaps for offering your help. l have added you as collaborators for starters. Could you please get in touch with me through email (me@svenfuchs.com), so we can sort out the rest?

**Comment by kuroda** [comment]
@svenfuchs Thank you for your warm words.
