### ISSUE TITLE
undetermined time in formatting

### ISSUE THREAD

**Issue by diego-fin** [svenfuchs/rails-i18n#988]
We have an undetermined time formatting shown in our app

For example, if the record is created with the following timezone:
`created_at: Fri, 07 Jan 2022 13:12:43.087666000 -03 -03:00`

In our config/locale we have defined, the following formatting
```
  time:
    formats:
      full_date_and_time: "%e de %B de %Y a las %k:%M"
```

so in the screen we are using it like this:

`<%= I18n.l notification.created_at, format: :full_date_and_time %>`

Then almost always the date is shown in the correct way, but sometimes when we refresh the page we see the time with another timezone. Then, if we refresh the page, it is shown with the correct timezone again.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/86374595/159300066-408db576-ef6b-45c5-aef1-55ea81c7ab03.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/86374595/159300023-912c921c-044e-4fda-819a-c4c2f03cb0e3.png">

It looks like there is a problem with the use of `%k` in the formatting.
Many thanks in advance!

**Comment by pama** [comment]
Hi @diego-fin, I don't think your question belongs here. Please try https://discuss.rubyonrails.org or StackOverflow.
