### ISSUE TITLE
Fix the specs (CY translation)

### ISSUE THREAD

**Issue by MoskitoHero** [svenfuchs/rails-i18n#990]
We have just updated the CI to use Github actions. Currently, the specs fail on the `cy.yml` file with this message:

```
1) a rails-i18n rails/locale/cy.yml locale file is expected not to have missing particular pluralization keys
     Failure/Error: it { should_not have_missing_particular_pluralization_keys }

       expected rails/locale/cy.yml to contain the following pluralization keys :
       - cy.errors.template.header.zero
       - cy.errors.template.header.few
     # ./spec/unit/translation_spec.rb:19:in `block (3 levels) in <top (required)>'
```

Can anyone with knowledge in the Welsh language take a look at this and see how to fix this?

**Comment by digitalfrost** [comment]
I see two possible solutions:
- remove the cy locale for the moment and add it back at a later date if we get help from a welsh speaker. See #1007
- Add the missing keys with English instead of Welsh for the values

@kuroda do you have an opinion as to which option we should follow.

**Comment by digitalfrost** [comment]
#1007 has been merged so I am closing this issue.
