### ISSUE TITLE
Tag your releases please

### ISSUE THREAD

**Issue by johnnyshields** [svenfuchs/rails-i18n#995]
The releases on Ruby gems (latest one 7.0.3) are not tagged in Github. This makes it difficult for me as an app maintainer to know what version of the code I am working with.

**Comment by mikinovation** [comment]
I have same problem

However, I used

`gem 'rails-i18n', github: 'svenfuchs/rails-i18n', branch: 'master'`

it worked now. I can't help to do it

**Comment by pama** [comment]
It seems that it hasn't been a practice to tag releases. Am I correct?

**Comment by mikinovation** [comment]
Yes, I think it was released at once but it has been cancelled 🤔

**Comment by johnnyshields** [comment]
The point of tagging releases is for us to know where in the code a specific Rubygems release is pointing to.

Suppose I am using version 1.0.0, and I want to upgrade to version 2.0.0. I should be able to do:

https://github.com/svenfuchs/rails-i18n/compare/v1.0.0...v2.0.0

and see a diff of the changes.

**Comment by pama** [comment]
We will add them from now on.

**Comment by johnnyshields** [comment]
Thank you 🙇‍♂️
