### ISSUE TITLE
I18n.localize changes the resource time zone

### ISSUE THREAD

**Issue by rgaufman** [svenfuchs/rails-i18n#999]
When I have just:

```
resource.starts_at
```

I see this in my browser:

```
2022-04-24T15:00:00.0007
```

I would like to format this to "15:00:00", so I run:

```
I18n.localize('date.formats.events_time_format', resource.starts_at)
```

However instead of 15:00:00 it shows me 16:00:00 -- how can I get it to show me 15:00:00 please?

**Comment by pama** [comment]
Hi @rgaufman, I recommend you to try the Rails Forums at https://discuss.rubyonrails.org. Other websites that can be useful:

* https://guides.rubyonrails.org/i18n.html
* https://github.com/ruby-i18n/i18n
* https://ruby-doc.org/stdlib-3.1.2/libdoc/date/rdoc/DateTime.html#method-i-strftime
* https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html
* http://danilenko.org/2012/7/6/rails_timezones/
* https://thoughtbot.com/blog/its-about-time-zones

Happy coding!

**Comment by rgaufman** [comment]
It appears to be a recent bug as it is working correctly before running bundle update.

**Comment by rgaufman** [comment]
If anyone has this same problem, I added this as a workaround, but looking for a better solution in the links you suggested, thank you.

I added this to my javascript (jsx) code:

```
 { I18n.localize('date.formats.events_time_format', resource.starts_at.slice(0, -1)) }
```

This works but not a great workaround, will update this comment if I find anything better.

**Comment by rgaufman** [comment]
This actually appears to be an i18n-js bug, opened here: https://github.com/fnando/i18n-js/issues/647 - all the Ruby methods work as expected.
